// =========================================================================================
// ========================== !!! USER: DO NOT EDIT THIS FILE !!! ==========================
// =========================================================================================

// Header file
#include "feathergauge_code.h"

// ===========================
// LIBRARIES
// =========================== 

// A note on using the SparkFun library:
// A very minor change to the SparkFun library is needed for this code to work. The sensorWait function in SparkFun_MS5803_I2C.h must be declared as virtual.
// This change is used to override sensorWait for better power management.

// Create custom MS5803 class to override sensorWait function for better power management
class CustomMS5803 : public MS5803 {
  public:
    void sensorWait(uint8_t time) {
      // sensorWait in SparkFun library is 1-10ms; the minimum sleep time is 16ms; In this sketch 
      // timer 0 wakes MCU from idle after 1 ms regardless of sleep time.
      // Turn off everything except timer 0 (used for millis), timer 1 (used for sampling),
      // and TWI (used to communicate with pressure sensor). ADC, timer 3, and timer 4 are set to
      // ON so LowPower library doesn't accidentally turn them back on, they are already off
      LowPower.idle(SLEEP_15MS, ADC_ON, TIMER4_ON, TIMER3_ON, TIMER1_ON, TIMER0_ON, SPI_OFF, 
                    USART1_OFF, TWI_ON, USB_OFF);
    }
};

// Timer 4 PRR bit is currently not defined in iom32u4.h
#ifndef PRTIM4
  #define PRTIM4 4  // Power Reduction Register bit for Timer 4
#endif

// Timer 4 power reduction macro is not defined currently in power.h, define it manually
// This macro manipulates the MCU registers to disable timer 4
#ifndef power_timer4_disable
  #define power_timer4_disable()	(PRR1 |= (uint8_t)(1 << PRTIM4))
#endif

// This macro manipulates the MCU registers to enable timer 4
#ifndef power_timer4_enable
  #define power_timer4_enable()		(PRR1 &= (uint8_t)~(1 << PRTIM4))
#endif

// Shared constants, structs, extern declarations, and function declarations.
#include "feathergauge_code.h"

// ===========================
// GLOBAL VARIABLE INITIALIZATION
// ===========================
#if DELAY_START
  bool hasStarted = false;
#endif

#if USE_NEW_SENSOR
  MS5837 newSensor;
#else
  MS5803 oldSensor;
#endif

#if BURST_SAMPLING
  TimeSpan elapsed;
#endif

RTC_DS3231 rtc;
File outputFile;            // Used to open, write to, and close files on the SD card

// Circular buffer variables
DataPoint dataBuffer[BUFFER_SIZE];
int bufferHead        = 0;  // Points to next write position
int bufferTail        = 0;  // Points to next read position
int bufferCount       = 0;  // Number of items in buffer
bool bufferOverflow   = false; // Flag to indicate buffer overflow

DateTime timeAtBurstSwitch; // Time burst switched between sleep and record
DateTime currentDateTime;     // Time of current second
float currentVoltage;       // Voltage of battery, updated every second

// Sampling flag for ISR to main loop communication
volatile bool samplingFlag   = false;
volatile bool resetTimerFlag = false;
volatile bool burstSleepFlag = false;
volatile bool sleeping       = false;

// Number of milliseconds at last 1 Hz interrupt from RTC
unsigned long millisAtInterrupt = 0; 

// # of times the LED should be toggled (on->off = 1 toggle) during the start-up verification phase
uint8_t ledWarmupToggleTarget = 0;

// Current # of times the LED has been toggled
uint8_t ledWarmupToggleCount  = 0;

// True if LED should be toggled only once during start-up
bool ledWarmupManualPulsePending = false;

// ===========================
// SETUP - SENSOR, TIMESTAMP, SD CARD
// ===========================

void setup() {
  power_timer3_disable();
  power_timer4_disable();
  pinMode(LED_PIN, OUTPUT);
  configureLedWarmupIndicator();
  Serial.end();
  // Serial.begin(SERIAL_BAUD_RATE);  // Commented out to prevent blocking when USB disconnected
  // while (!Serial);                 // Commented to prevent blocking when USB disconnected 
  Wire.begin();
  Wire.setClock(TWI_CLOCK_SPEED);

  // DS3231 SQW pin requires an external pull-up resistor. The internal pull-up resistors 
  // included in the 32u4 are too weak for square wave oscillator output but interrupts still work.
  pinMode(RTC_INTERRUPT_PIN, INPUT_PULLUP);
  
  if (!rtc.begin()) {
    if (Serial) Serial.println(F("RTC Failed to initialize"));
    error(2);
    return;
  }
  rtc.disable32K();
  rtc.clearAlarm(1);
  rtc.clearAlarm(2);
  rtc.writeSqwPinMode(DS3231_OFF);

  if (rtc.lostPower()) {
        // This will adjust to the date and time at compilation; recompile everytime MCU is 
        // flashed for accuracy. If the DS3231 has had continous MCU/button battery power since 
        // last program flash, the time will not be changed.

        // **Relying on this to set the correct time is a bad idea**, but it's better than 
        // no date at all
        rtc.adjust(DateTime(F(__DATE__), F(__TIME__)));
        if (Serial) {
          DateTime setTime = rtc.now();
          Serial.print(F("RTC time set to: "));
          Serial.print(setTime.year());
          Serial.print('/');
          Serial.print(setTime.month());
          Serial.print('/');
          Serial.print(setTime.day());
          Serial.print(' ');
          Serial.print(setTime.hour());
          Serial.print(':');
          Serial.print(setTime.minute());
          Serial.print(':');
          Serial.println(setTime.second());
        }
  }
  
  #if USE_NEW_SENSOR
    if (!newSensor.init()) {
      if (Serial) Serial.println("New pressure sensor failed to initialize");
      error(3);
      return;
    }
    newSensor.setModel(MS5837::MS5837_02BA);
    newSensor.setFluidDensity(FRESHWATER_DENSITY);
  #else
    oldSensor.reset();
    oldSensor.begin();
  #endif

  if (Serial) Serial.print(F("Initializing SD card..."));
  
  if (!SD.begin(SD_CARD_SELECT_PIN)) { 
    if (Serial) Serial.println(F("Card Failed or Not Present"));
    error(ERROR_SD_CARD_FAILED);
    return;
  }
  
  for (int i = 0; i < BUFFER_SIZE; i++) {
    dataBuffer[i].valid = false;
  }

  if (Serial) Serial.println(F("Card Initialized."));
  char fileName[FILENAME_LENGTH];
  makeFileName(fileName);
  
  SdFile::dateTimeCallback(setTimeStamp); // Timestamps the .csv file (inserts as metadata)
  outputFile = SD.open(fileName, FILE_WRITE); // Opens .csv file

  if (outputFile) {
    if (Serial) Serial.println(F("File opened"));
    char serialNumber[16];
    EEPROM.get(SERIAL_NUMBER_ADDRESS, serialNumber);
    outputFile.print(F("W.G. Num: "));
    outputFile.print(serialNumber);
    outputFile.print(',');
    outputFile.print(F("Timestamp,Pressure [mbar],Temp [deg C],Battery [VDC]"));
    outputFile.println();
    outputFile.flush();
  } else {
    if (Serial) Serial.println(F("error opening datalog-case1"));
    error(ERROR_FILE_OPEN_FAILED);
  }

  currentDateTime = rtc.now();
  currentVoltage = getBatteryVoltage();
  power_adc_disable();

  rtc.disableAlarm(2);
  #if DELAY_START
    delayStartDeepSleepLoop();
    power_adc_enable();
    currentDateTime = rtc.now();
    currentVoltage = getBatteryVoltage();
    power_adc_disable();
  #endif
  // Set alarm to go off 1 second from now, DS3231_A1_PerSecond triggers alarm when seconds match
  rtc.clearAlarm(1);
  rtc.setAlarm1(currentDateTime + TimeSpan(1), DS3231_A1_PerSecond); 
  #if !(BURST_SAMPLING && BURST_SAMPLING_ONE_SAMPLE)
    Timer1.initialize(SAMPLE_TIME);
    Timer1.attachInterrupt(triggerSampling); // Every time Timer1 goes off, calls triggerSampling
    attachInterrupt(digitalPinToInterrupt(RTC_INTERRUPT_PIN), resetTimerInterrupt, FALLING);
  #endif
  millisAtInterrupt = millis();
  #if BURST_SAMPLING
    timeAtBurstSwitch = currentDateTime;
    if (Serial) {
      Serial.print(F("[BURST] Start write window at "));
      Serial.print(timeAtBurstSwitch.hour()); Serial.print(':');
      Serial.print(timeAtBurstSwitch.minute()); Serial.print(':');
      Serial.println(timeAtBurstSwitch.second());
      Serial.print(F("[BURST] writeSeconds=")); Serial.print(writeSeconds);
      Serial.print(F(", sleepSeconds=")); Serial.println(sleepSeconds);
    }
  #endif
}

// ===========================
// DATA COLLECTION LOOP
// ===========================

void loop() {
    #if BURST_SAMPLING
      // If true, write time ended; write to SD card and sleep
      if (burstSleepFlag) {
        timeAtBurstSwitch = rtc.now();
        #if !BURST_SAMPLING_ONE_SAMPLE
          Timer1.stop();
          attachInterrupt(digitalPinToInterrupt(RTC_INTERRUPT_PIN), resetTimerInterrupt, FALLING);
        #endif
        resetTimer();
        if (Serial) {
          Serial.print(F("[BURST] Wake -> start write window at "));
          Serial.print(timeAtBurstSwitch.hour()); Serial.print(':');
          Serial.print(timeAtBurstSwitch.minute()); Serial.print(':');
          Serial.println(timeAtBurstSwitch.second());
        }
        burstSleepFlag = false;
      } else if (elapsed.totalseconds() > writeSeconds || BURST_SAMPLING_ONE_SAMPLE) {
        #if BURST_SAMPLING_ONE_SAMPLE
          performSensorReading();
        #endif
        DateTime endTime = rtc.now();
        DataPoint data;
        while (readFromBuffer(&data)) {
          writeToOutputFile(data.now, data.millisec, data.pressure, data.temperature, 
                            data.batteryVoltage);
        }
        outputFile.flush();
        if (Serial) {
          Serial.print(F("[BURST] End write window at "));
          Serial.print(endTime.hour()); Serial.print(':');
          Serial.print(endTime.minute()); Serial.print(':');
          Serial.println(endTime.second());
          Serial.print("Elapsed time: ");
          Serial.println(elapsed.totalseconds());
        }
        enterBurstDeepSleep(endTime);
      }
    #endif

    if (resetTimerFlag) {
      resetTimer();
      resetTimerFlag = false;
    }

    if (samplingFlag) {
      #if !(BURST_SAMPLING && BURST_SAMPLING_ONE_SAMPLE)
        performSensorReading();
      #endif
      samplingFlag = false;
    }

    if (bufferCount > BUFFER_WRITE_COUNT - 1) {
      DataPoint data;
      int writeCount = 0;
      while (readFromBuffer(&data) && writeCount < BUFFER_WRITE_COUNT) {
        writeToOutputFile(data.now, data.millisec, data.pressure, data.temperature, 
                          data.batteryVoltage);
        writeCount++;
        if (samplingFlag) {
          performSensorReading();
          samplingFlag = false;
        }
      }
      if (Serial) {
        Serial.print(F("Starting write at time: "));
        Serial.println(millis());
      }
      outputFile.flush();
      if (Serial) {
        Serial.print(F("Wrote "));
        Serial.print(writeCount);
        Serial.print(F(" data points to SD card at time "));
        Serial.println(millis());
      }
    }
    // Finished writing to SD card, sleep until next sampling time or interrupt from timers/RTC
    // When waking from burst sleep, this idle command mean the MCU will sleep until the next ms, 
    // then check the burst flag
    setForeverIdleSleep();
}

// ===========================
// DATA ACQUISITION FUNCTIONS
// ===========================
void performSensorReading() {
    float currentTemperature, currentPressure;
    #if USE_NEW_SENSOR
      newSensor.read();
      currentTemperature = newSensor.temperature();
      currentPressure = newSensor.pressure();
    #else
      oldSensor.getSensorReadings(CELSIUS, ADC_4096, ADC_2048, &currentPressure, 
                                  &currentTemperature);
    #endif

  updateLedWarmupIndicator();
    // Compute timestamp relative to last RTC tick without mutating global currentDateTime
    uint16_t millisec = millis() - millisAtInterrupt;
    DateTime now = currentDateTime;
    // while (millisec >= 1000) {
    //   millisec -= 1000;
    //   now = now + TimeSpan(1);
    // }

    addToBuffer(now, millisec, currentPressure, currentTemperature, currentVoltage);
}

float getBatteryVoltage() {
  int sensorValue = analogRead(BATTERY_VOLTAGE_PIN);
  float batteryVoltage = (sensorValue * REFERENCE_VOLTAGE) / MAX_ADC_VALUE;
  // Adjust multiplier based on your divider
  float actualBatteryVoltage = batteryVoltage * BATTERY_VOLTAGE_MULTIPLIER;
  return actualBatteryVoltage;
}

// ===========================
// RTC/TIME/SD UTILITIES
// ===========================

void resetTimer() {
  power_adc_enable();
  millisAtInterrupt = millis();
  currentDateTime = rtc.now();
  if (Serial) {
    Serial.print(F("Reset timer at: "));
    Serial.print(currentDateTime.year());
    Serial.print('/');
    Serial.print(currentDateTime.month());
    Serial.print('/');
    Serial.print(currentDateTime.day());
    Serial.print(' ');
    Serial.print(currentDateTime.hour());
    Serial.print(':');
    Serial.print(currentDateTime.minute());
    Serial.print(':');
    Serial.println(currentDateTime.second());
  }
  #if BURST_SAMPLING
    elapsed = currentDateTime - timeAtBurstSwitch;
  #endif
  currentVoltage = getBatteryVoltage();
  #if !(BURST_SAMPLING && BURST_SAMPLING_ONE_SAMPLE)
    rtc.clearAlarm(1);
    // rtc.setAlarm1(currentDateTime + TimeSpan(1), DS3231_A1_PerSecond);
  #endif
  power_adc_disable();
}


void makeFileName(char* fileName) {
  // Format: MM-DD-00.csv (e.g., 04-23-01.csv)
  DateTime now = rtc.now();
  
  // Build filename: MM-DD-
  fileName[0] = '0' + (now.month() / 10);
  fileName[1] = '0' + (now.month() % 10);
  fileName[2] = '-';
  fileName[3] = '0' + (now.day() / 10);
  fileName[4] = '0' + (now.day() % 10);
  fileName[5] = '-';
  fileName[6] = '0';
  fileName[7] = '0';
  fileName[8] = '.';
  fileName[9] = 'c';
  fileName[10] = 's';
  fileName[11] = 'v';
  fileName[12] = '\0';
  // Find the next available file index for this day
  for (uint8_t fileIndex = 1; fileIndex < 100; fileIndex++) {
    if (!SD.exists(fileName)) {
      break;
    }
    fileName[6] = '0' + (fileIndex / 10);
    fileName[7] = '0' + (fileIndex % 10);
  }
  
  if (Serial) {
    Serial.print(F("File name: "));
    Serial.println(fileName);
  }
}

void setTimeStamp(uint16_t* date, uint16_t* time) {
  DateTime now = rtc.now();
  *date = FAT_DATE(now.year(), now.month(), now.day());
  *time = FAT_TIME(now.hour(), now.minute(), now.second());
}

void writeToOutputFile(DateTime now, int millisec, float pressure, 
                       float temperature, float batteryVoltage) {
  // Write data to SD card
  outputFile.print(now.year());
  outputFile.print('/');
  outputFile.print(now.month());
  outputFile.print('/');
  outputFile.print(now.day());
  outputFile.print(",");
  outputFile.print(now.hour());
  outputFile.print(':');
  if (now.minute() < 10) {
    outputFile.print("0");
  }
  outputFile.print(now.minute());
  outputFile.print(':');
  if (now.second() < 10) {
    outputFile.print("0");
  }
  outputFile.print(now.second());
  outputFile.print(':');
  if (millisec < 10) {
    outputFile.print("00");
  } else if (millisec < 100) {
    outputFile.print("0");
  }
  outputFile.print(millisec);
  outputFile.print(",");
  outputFile.print(pressure);
  outputFile.print(",");
  outputFile.print(temperature);
  outputFile.print(",");
  outputFile.print(batteryVoltage);
  outputFile.println();
}

// ===========================
// CIRCULAR BUFFER FUNCTIONS
// ===========================

void addToBuffer(DateTime now, int millisec, float pressure, float temperature, 
                  float batteryVoltage) {
  if (bufferCount >= BUFFER_SIZE) {
    bufferTail = (bufferTail + 1) % BUFFER_SIZE;
  } else {
    bufferCount++;
  }
  dataBuffer[bufferHead].now = now;
  dataBuffer[bufferHead].millisec = millisec;
  dataBuffer[bufferHead].pressure = pressure;
  dataBuffer[bufferHead].temperature = temperature;
  dataBuffer[bufferHead].batteryVoltage = batteryVoltage;
  dataBuffer[bufferHead].valid = true;
  
  bufferHead = (bufferHead + 1) % BUFFER_SIZE;
}

bool readFromBuffer(DataPoint* data) {
  if (bufferCount == 0) {
    return false; // Buffer is empty
  }
  
  // Copy data from buffer
  data->now = DateTime(dataBuffer[bufferTail].now.unixtime());
  data->millisec = dataBuffer[bufferTail].millisec;
  data->pressure = dataBuffer[bufferTail].pressure;
  data->temperature = dataBuffer[bufferTail].temperature;
  data->batteryVoltage = dataBuffer[bufferTail].batteryVoltage;
  data->valid = dataBuffer[bufferTail].valid;
  
  // Mark as invalid and move tail
  dataBuffer[bufferTail].valid = false;
  bufferTail = (bufferTail + 1) % BUFFER_SIZE;
  bufferCount--;
  
  return data->valid;
}

// ===========================
// SLEEP MANAGEMENT
// ===========================


// When time is set into the future, no sensor readings occur
void delayStartDeepSleepLoop() {
  DateTime startDateTime(startYear, startMonth, startDay, startHour, startMinute, 0);

  // Configure RTC alarms
  rtc.clearAlarm(1);
  attachInterrupt(digitalPinToInterrupt(RTC_INTERRUPT_PIN), deepSleepInterrupt, FALLING);
  rtc.setAlarm1(startDateTime, DS3231_A1_Hour); // Alarm 1 triggers every day until start time

  // Don't go to sleep if start time has already passed
  DateTime now = rtc.now();

  if (now.unixtime() >= startDateTime.unixtime()) {
    detachInterrupt(digitalPinToInterrupt(RTC_INTERRUPT_PIN));
    rtc.clearAlarm(1);
    return;
  }
  if (Serial) Serial.println(F("Entering delay deep sleep"));

  // Loop until start date is reached
  while (true) {
    // ADC is OFF; ADC_ON setting prevents LowPower from turning it back on after waking up
    LowPower.powerDown(SLEEP_FOREVER, ADC_ON, BOD_OFF);
    delay(50);  // This delay allows MCU components to initialize upon wake-up
    Wire.end(); // The delay, and restarting I2C isn't strictly necessary but qualitatively improves stability
    Wire.begin();
    Wire.setClock(TWI_CLOCK_SPEED);
    // Device has woken up
    now = rtc.now();
    if (now.unixtime() >= startDateTime.unixtime()) {
      detachInterrupt(digitalPinToInterrupt(RTC_INTERRUPT_PIN));
      rtc.clearAlarm(1);
      return; // Exit loop and continue with setup()
    }

    digitalWrite(LED_PIN, HIGH);
    delay(ERROR_BLINK_DELAY);
    digitalWrite(LED_PIN, LOW);
    
    // Not yet at start date, log one sample and go back to sleep
    power_adc_enable();
    performSensorReading();
    // Perform voltage reading after sensor reading to give ADC time to settle
    currentVoltage = getBatteryVoltage(); 
    power_adc_disable();
    DataPoint data;
    readFromBuffer(&data);
    // Don't use batteryVoltage or current date from buffer because it is not updated in deep sleep mode
    writeToOutputFile(now, 0, data.pressure, data.temperature, currentVoltage);
    outputFile.flush();
    rtc.clearAlarm(1);
  }
}

void enterDelayDeepSleep() {
  // Set RTC alarm to correct date
  // Serial.println(F("Entering RTC deep sleep"));
  DateTime startDateTime(startYear, startMonth, startDay, startHour, startMinute, 0);
  rtc.clearAlarm(1);
  rtc.clearAlarm(2);
  attachInterrupt(digitalPinToInterrupt(RTC_INTERRUPT_PIN), deepSleepInterrupt, FALLING);
  rtc.setAlarm1(startDateTime, DS3231_A1_Date); // Alarm 1 triggers at the start time
  rtc.setAlarm2(startDateTime, DS3231_A2_Hour); // Alarm 2 triggers every day, taking a sample to track when/if battery dies
  if (Serial) Serial.println(F("Entering delay deep sleep"));
  // LowPower libraries reenables peripheerals set to OFF, even if they were initially disabled
  // ADC is currently disabled, so setting `ADC_ON` keeps it disabled even after waking up
  LowPower.powerDown(SLEEP_FOREVER, ADC_ON, BOD_OFF);
}

void enterBurstDeepSleep(DateTime endTime) {
  rtc.clearAlarm(1);
  DateTime now = rtc.now();
  if (now.unixtime() > endTime.unixtime() + sleepSeconds) {
    timeAtBurstSwitch = rtc.now();
    resetTimer();
    attachInterrupt(digitalPinToInterrupt(RTC_INTERRUPT_PIN), resetTimerInterrupt, FALLING);
    #if !BURST_SAMPLING_ONE_SAMPLE
      Timer1.initialize(SAMPLE_TIME);
      Timer1.attachInterrupt(triggerSampling);
    #endif
    burstSleepFlag = true;
    return;
  }
  DateTime nextWake(endTime + TimeSpan(sleepSeconds));
  if (Serial) {
    Serial.print(F("[BURST] Next wake scheduled at "));
    Serial.print(nextWake.hour()); Serial.print(':');
    Serial.print(nextWake.minute()); Serial.print(':');
    Serial.println(nextWake.second());
  }
  rtc.clearAlarm(1);
  rtc.setAlarm1(nextWake, DS3231_A1_Date);
  attachInterrupt(digitalPinToInterrupt(RTC_INTERRUPT_PIN), burstSleepInterrupt, FALLING);

  // ADC is OFF; ADC_ON setting prevents LowPower from turning it back on after waking up
  LowPower.powerDown(SLEEP_FOREVER, ADC_ON, BOD_OFF);
  delay(50);  // This delay is important to allow MCU components to initialize upon wake-up
  Wire.end();
  Wire.begin();
  Wire.setClock(TWI_CLOCK_SPEED);
  rtc.clearAlarm(1);
  timeAtBurstSwitch = rtc.now();
  resetTimer();
  attachInterrupt(digitalPinToInterrupt(RTC_INTERRUPT_PIN), resetTimerInterrupt, FALLING);
  #if !BURST_SAMPLING_ONE_SAMPLE
    Timer1.initialize(SAMPLE_TIME);
    Timer1.attachInterrupt(triggerSampling);
  #endif
}

void setForeverIdleSleep() {
  // ADC, timer 3, and timer 4 are set to ON so LowPower library doesn't turn them back on afer 
  // sleep, they are already off
  LowPower.idle(SLEEP_FOREVER, ADC_ON, TIMER4_ON, TIMER3_ON, TIMER1_ON, TIMER0_ON, SPI_OFF, USART1_OFF, 
                TWI_ON, USB_OFF);
}

// ===========================
// ERRORS/TROUBLESHOOTING
// ===========================

void error (uint8_t errno) {
  while (1) {
    uint8_t blinkCount; // Counts error blinks
    for (blinkCount = 0; blinkCount < errno; blinkCount++) {
      digitalWrite(LED_PIN, HIGH);
      delay(ERROR_BLINK_DELAY);
      digitalWrite(LED_PIN, LOW);
      delay(ERROR_BLINK_DELAY);
    }
    for (blinkCount = errno; blinkCount < ERROR_BLINK_CYCLE; blinkCount++) {
      delay(ERROR_PAUSE_DELAY);
    }
  }
}

void configureLedWarmupIndicator() {
  ledWarmupToggleCount = 0;
  ledWarmupToggleTarget = 0;
  ledWarmupManualPulsePending = false;

#if BURST_SAMPLING_ONE_SAMPLE
  ledWarmupManualPulsePending = true;
#else
  uint8_t flashCount = LED_WARMUP_DEFAULT_FLASHES;
  bool useManualPulse = false;
  #if BURST_SAMPLING
    uint32_t availableReadings = (uint32_t)writeSeconds * (uint32_t)SAMPLE_FREQ;
    // Calculate # of flashes that fit within first sampling window
    while (flashCount > 1 && ((uint32_t)flashCount * 2) > availableReadings) {
      flashCount /= 2;
      if (flashCount == 0) {
        flashCount = 1;
        break;
      }
    }
    if (((uint32_t)flashCount * 2) > availableReadings) {
      useManualPulse = true;
    }
  #endif
  if (useManualPulse) {
    ledWarmupManualPulsePending = true;
  } else {
    ledWarmupToggleTarget = flashCount * 2;
  }
#endif

  digitalWrite(LED_PIN, LOW);
}

void updateLedWarmupIndicator() {
  if (ledWarmupManualPulsePending) {
    digitalWrite(LED_PIN, HIGH);
    delay(LED_WARMUP_MANUAL_FLASH_DELAY_MS);
    digitalWrite(LED_PIN, LOW);
    ledWarmupManualPulsePending = false;
    return;
  }

  if (ledWarmupToggleCount >= ledWarmupToggleTarget) {
    return;
  }

  bool ledShouldBeOn = (ledWarmupToggleCount % 2 == 0);
  digitalWrite(LED_PIN, ledShouldBeOn ? HIGH : LOW);
  ledWarmupToggleCount++;

  if (ledWarmupToggleCount >= ledWarmupToggleTarget) {
    digitalWrite(LED_PIN, LOW);
  }
}

// ===========================
// INTERRUPT SERVICE ROUTINES
// ===========================

void triggerSampling() {
    samplingFlag = true;
}

void resetTimerInterrupt() {
  resetTimerFlag = true;
}

void deepSleepInterrupt() {
  // Do nothing
}

void burstSleepInterrupt() {
  // Do nothing
}
