// =========================================================================================
// ========================== !!! USER: DO NOT EDIT THIS FILE !!! ==========================
// =========================================================================================

#ifndef FEATHERGAUGE_CODE_H
#define FEATHERGAUGE_CODE_H

// ===========================
// LIBRARIES
// =========================== 

#include "user_config.h"

#include <Wire.h>
#include <SPI.h>
#include <SdFat.h>
#include <EEPROM.h>
#include <avr/power.h>
#include <TimerOne.h>
#include <LowPower.h>

// INTERNAL WARNING - Ignore before January 1st, 2037
// RTClib uses a 32-bit variable to track time. After January 19th 2038, this value will overflow
// and the library will have to be updated to use 64-bit variables to continue using it.
// I will be very happy if this code is still being used in 2038. :) 
#include <RTClib.h>

#if USE_NEW_SENSOR
  #include "MS5837.h"
#else
  #include "SparkFun_MS5803_I2C.h"
#endif

// ===========================
// CLASSES
// ===========================

class MS5837;
class MS5803;

// Create custom MS5803 class to override sensorWait function for better power management
class CustomMS5803 : public MS5803 {
  public:
    void sensorWait(uint8_t time) {
      // sensorWait in SparkFun library is 1-10ms; the minimum sleep time is 16ms; In this sketch 
      // timer 0 wakes MCU from idle after 1 ms regardless of sleep time.
      // Turn off everything except timer 0 (used for millis), timer 1 (used for sampling),
      // and TWI (used to communicate with pressure sensor). ADC, timer 3, and timer 4 are set to
      // ON so LowPower library doesn't accidentally turn them back on, they are already off
      LowPower.idle(SLEEP_15MS, ADC_ON, TIMER4_ON, TIMER3_ON, TIMER1_ON, TIMER0_ON, SPI_OFF, 
                    USART1_OFF, TWI_ON, USB_OFF);
    }
};

// ===========================
// MACROS
// ===========================

// Timer 4 PRR bit is currently not defined in iom32u4.h
#ifndef PRTIM4
  #define PRTIM4 4  // Power Reduction Register bit for Timer 4
#endif

// Timer 4 power reduction macro is not defined currently in power.h, define it manually
// This macro manipulates the MCU registers to disable timer 4
#ifndef power_timer4_disable
  #define power_timer4_disable()	(PRR1 |= (uint8_t)(1 << PRTIM4))
#endif

// This macro manipulates the MCU registers to enable timer 4
#ifndef power_timer4_enable
  #define power_timer4_enable()		(PRR1 &= (uint8_t)~(1 << PRTIM4))
#endif

// ===========================
// CONSTANT DEFINITIONS
// ===========================

// Pin definitions
constexpr uint8_t LED_PIN                        = 13;        // Built-in LED pin for status indication
constexpr uint8_t RTC_INTERRUPT_PIN              = 1;         // RTC alarm interrupt pin (DS3231 SQW)
constexpr uint8_t SD_CARD_SELECT_PIN             = 4;         // SPI chip select pin for SD card
constexpr uint8_t BATTERY_VOLTAGE_PIN            = A9;        // Analog pin for battery voltage measurement

// Timing and frequency definitions
constexpr unsigned long MICROSECONDS_PER_SECOND  = 1000000UL; // Conversion factor for time calculations
constexpr float SAMPLE_TIME                      = (1.0f / SAMPLE_FREQ) * MICROSECONDS_PER_SECOND;  // Timer1 period in microseconds
constexpr unsigned long TWI_CLOCK_SPEED          = 400000UL;  // I2C communication speed (400kHz)
constexpr unsigned long SERIAL_BAUD_RATE         = 57600UL;   // Serial communication speed for debugging
constexpr uint8_t ERROR_BLINK_DELAY              = 100;       // LED on/off time during error indication (ms)
constexpr uint8_t ERROR_PAUSE_DELAY              = 200;       // Pause between error blink cycles (ms)
constexpr uint8_t ERROR_BLINK_CYCLE              = 10;        // Total blinks per error cycle

const uint8_t LED_WARMUP_DEFAULT_FLASHES         = 6;         // Number of expected flashes from sensor readings at program start
const uint16_t LED_WARMUP_MANUAL_FLASH_DELAY_MS  = 100;       // How long the single flash at program start for one-sample burst

// ADC and voltage definitions used for measuring battery voltage
constexpr uint16_t MAX_ADC_VALUE                 = 1023;      // Maximum ADC reading (10-bit resolution)
constexpr float REFERENCE_VOLTAGE                = 3.3f;      // ADC reference voltage (V)
constexpr uint8_t BATTERY_VOLTAGE_MULTIPLIER     = 2;         // Voltage divider compensation factor

// Evaluated  at compile-time to eliminate floating-point overhead w/ battery voltage reading.
// The base formula is: voltage = ((sensorValue * REFERENCE_VOLTAGE) / MAX_ADC_VALUE) * BATTERY_VOLTAGE_MULTIPLIER
//
// This constant pre-calculates that formula while applying two scaling factors:
// 1. Multiplied by 100 to preserve two decimal places (fixed-point conversion).
// 2. Multiplied by 2^16 (65536) to allow for bit-shift division at runtime.
//
// Runtime execution is reduced to three integer operations:
// 1. Multiply the ADC reading by this constant.
// 2. Add 32768 (half of 2^16) to ensure accurate rounding.
// 3. Bit-shift right by 16 (>> 16), which executes division by 2^16 in zero clock cycles.
constexpr uint32_t BATT_FAST_MULT = (uint32_t)((((REFERENCE_VOLTAGE * BATTERY_VOLTAGE_MULTIPLIER * 100.0) / MAX_ADC_VALUE) * 65536.0) + 0.5);

// Buffer and data definitions
constexpr uint8_t FILENAME_LENGTH                = 27;        // Filename length, limited by LFN system to 256 characters
constexpr uint8_t ROW_BUFFER_SIZE                = 64;        // Current real row size is 45-46 bytes (43-44 data + CRLF)
constexpr uint8_t FLUSH_INTERVAL_SECONDS         = 10;        // Number of elapsed seconds between periodic SD flushes
constexpr uint32_t FILE_ROLLOVER_SIZE_BYTES      = 3800000000UL; // Max size of one CSV before rotating to next file
constexpr uint8_t SERIAL_NUMBER_LENGTH           = 16;        // Buffer length of the serial number in bytes, as stored in EEPROM
constexpr uint16_t FRESHWATER_DENSITY            = 997;       // Freshwater density (kg/m³) for pressure calculations
constexpr uint16_t SALTWATER_DENSITY             = 1025;      // Saltwater density (kg/m³) for pressure calculations

// Error code definitions
constexpr uint8_t ERROR_SD_CARD_FAILED           = 1;         // Error code for SD card initialization failure
constexpr uint8_t ERROR_FILE_OPEN_FAILED         = 2;         // Error code for file creation failure

constexpr uint8_t SERIAL_NUMBER_ADDRESS          = 0;         // EEPROM address for device serial number

// ===========================
// GLOBAL VARIABLE DECLARATIONS
// ===========================

// Declare start variables if not declared in user_config.h so that code compiles even if delay start
// isn't used
#if DELAY_START
  extern bool hasStarted;
#else
  const int START_YEAR   = 2000;
  const int START_MONTH  = 1;
  const int START_DAY    = 1;
  const int START_HOUR   = 12;
  const int START_MINUTE = 0;
#endif

#if USE_NEW_SENSOR
  extern MS5837 newSensor;
#else
  extern MS5803 oldSensor;
#endif

#if BURST_SAMPLING
  extern TimeSpan elapsed;
#endif

extern RTC_DS3231 rtc;
extern File32 outputFile;          // Used to open, write to, and close files on the SD card

extern DateTime timeAtBurstSwitch; // Time burst switched between sleep and record
extern DateTime currentDateTime;   // Time of current second; read/write from main must use noInterrupts()/interrupts()
extern int16_t currentVoltage;     // Voltage of battery, updated every second; fixed point X.XX

// Number of seconds elapsed since the last SD flush (incremented in resetTimer())
extern uint8_t secondsSinceFlush;

// Sampling flag for ISR to main loop communication
extern volatile bool samplingFlag;
extern volatile bool resetTimerFlag;

// Number of milliseconds at last 1 Hz interrupt from RTC; read/write from main must use noInterrupts()/interrupts()
extern volatile unsigned long millisAtInterrupt;

// # of times the LED should be toggled (switched between on/off) during the start-up verification phase
extern uint8_t ledWarmupToggleTarget;

// Current # of times the LED has been toggled
extern uint8_t ledWarmupToggleCount;

// True if LED should be toggled only once (blocking for LED_WARMUP_MANUAL_FLASH_DELAY_MS) during start-up
extern bool ledWarmupManualPulsePending;

// ===========================
// FUNCTION DECLARATIONS
// ===========================

/**
 * performSensorReading
 * Purpose: Read pressure and temperature from the active sensor and immediately write one CSV row.
 * Inputs:
 *   - None (uses globals: currentDateTime, millisAtInterrupt, currentVoltage)
 * Usage: Called when `samplingFlag` is set or in one-sample burst mode.
 * Note: currentDateTime and millisAtInterrupt are read with interrupts disabled to avoid races with resetTimerInterrupt().
 */
void performSensorReading();

/**
 * getBatteryVoltage
 * Purpose: Measure battery voltage via ADC on `BATTERY_VOLTAGE_PIN` using divider ratio.
 * Inputs: None
 * Returns: int16_t - battery voltage in volts, fixed point format X.XX
 * Usage: Call once per second or as needed; ADC MUST enabled/disabled by caller.
 */
int16_t getBatteryVoltage();

/**
 * resetTimer
 * Purpose: Synchronize timer-driven sampling to the RTC second tick; updates timekeeping and schedules next RTC alarm.
 * Inputs: None
 * Usage: Call after every RTC interrupt or when starting new sampling windows.
 * Note: Updates currentDateTime under noInterrupts() after rtc.now() to avoid races with resetTimerInterrupt().
 */
void resetTimer();

/**
 * makeFileName
 * Purpose: Generate a daily-rotating CSV filename in the form WG-SS_YYYY-MM-DD_IT-XX.csv.
 * Inputs:
 *   - fileName: char* (output) - caller-provided buffer of length FILENAME_LENGTH.
 *   - serialNumber: char* (input) - serial number string loaded from EEPROM.
 * Usage: Call once during setup before opening the SD file.
 */
void makeFileName(char* fileName, char* serialNumber);

/**
 * setFileTimestampOnce
 * Purpose: Set FAT metadata once for the opened SD file.
 * Inputs:
 *   - file: File32& (in/out) - opened file to timestamp.
 * Usage: Call immediately after opening the file to set create/write/access times one time
 *        from the RTC, without registering a callback that runs again on later sync/write operations.
 */
void setFileTimestampOnce(File32& file);

/**
 * writeToOutputFile
 * Purpose: Append one CSV line to the open SD file using fixed-point values and pointer arithmetic formatting.
 * Inputs:
 *   - now: DateTime - timestamp (date and time to seconds).
 *   - millisec: uint16_t - millisecond offset within the second (0..999, or 1000+ for overrun).
 *   - pressure: int32_t - pressure in tenths of mbar (XXXX.X).
 *   - temperature: int32_t - temperature in hundredths of degrees C (XX.XX).
 *   - batteryVoltage: int16_t - battery voltage in hundredths of volts (X.XX).
 * Usage: Call to write sensor reading to file.
 */
void writeToOutputFile(DateTime now, uint16_t millisec, int32_t pressure, int32_t temperature, int16_t batteryVoltage);

/**
 * enterDelayDeepSleep
 * Purpose: Configure RTC alarms for the target start date/time and enter deep sleep until then.
 * Inputs: None
 * Usage: Used when DELAY_START is enabled.
 */
void enterDelayDeepSleep();

/**
 * enterBurstDeepSleep
 * Purpose: Schedule next wake time after a burst write window and enter deep sleep until then.
 * Inputs:
 *   - endTime: DateTime — timestamp when the last write window ended.
 * Usage: Used only when BURST_SAMPLING is enabled.
 */
void enterBurstDeepSleep(DateTime endTime);

/**
 * setForeverIdleSleep
 * Purpose: Enter idle sleep indefinitely while keeping timers 0/1 running for millis tracking and sampling cadence.
 * Inputs: None
 * Usage: Use at end of loop to minimize power between events while preserving timer state.
 */
void setForeverIdleSleep();

/**
 * error
 * Purpose: Indicate unrecoverable error by blinking LED a number of times equal to `errno`, repeated forever.
 * Inputs:
 *   - errno: uint8_t — error code and blink count.
 * Usage: Call on fatal conditions; function does not return.
 */
void error(uint8_t errno);

/**
 * configureLedWarmupIndicator
 * Purpose: Set the correct number of flashes at start-up for the current configuration, used to verify
 *          that the wave gauge is working correctly without serial port access.
 * Inputs: None, configures global variables ledWarmupToggleCount, ledWarmupToggleTarget, ledWarmupManualPulsePending
 * Usage: Run once within setup()
 */
void configureLedWarmupIndicator();

/**
 * updateLedWarmupIndicator
 * Purpose: Toggle LED_PIN at program start for a set number of sensor readings
 * Inputs: None, uses global variables ledWarmupToggleCount, ledWarmupToggleTarget, ledWarmupManualPulsePending
 * Usage: Run within performSensorReadings() if LED diagnostics are desired
 */
void updateLedWarmupIndicator();

/**
 * triggerSampling (ISR context)
 * Purpose: Flag main loop to perform a sensor read (Timer1 compare interrupt).
 * Inputs: None
 */
void triggerSampling();

/**
 * resetTimerInterrupt (ISR context)
 * Purpose: Flag main loop to resynchronize timers on each RTC second tick. Also updates 
 * millisAtInterrupt and pre-emptively increments currentDateTime by one second, pending actual
 * I2C correction in resetTimer(). Main code must read/write currentDateTime and millisAtInterrupt with interrupts disabled.
 * 
 * Inputs: None
 */
void resetTimerInterrupt();

/**
 * deepSleepInterrupt (ISR context)
 * Purpose: Flag main loop that the RTC alarm fired during delay-start deep sleep.
 * Inputs: None
 */
void deepSleepInterrupt();

/**
 * burstSleepInterrupt (ISR context)
 * Purpose: Flag main loop that the RTC alarm fired to end burst sleep.
 * Inputs: None
 */
void burstSleepInterrupt();

// ASCII arithmetic functions used to convert sensor readings into a saveable format

// Appends a variable-length integer to ptr and advances ptr past the written digits.
static inline void appendInt(char*& ptr, int val) {
  itoa(val, ptr, 10);
  while (*ptr) ptr++;
}

// Appends a variable-length 32-bit integer to ptr and advances ptr past the written digits.
static inline void append32Int(char*& ptr, int32_t val) {
  ltoa(val, ptr, 10);
  while (*ptr) ptr++;
}

// Appends a fixed 2-digit zero-padded integer (0-99) using direct ASCII math.
static inline void appendPadded2(char*& ptr, int val) {
  *ptr++ = '0' + (val / 10);
  *ptr++ = '0' + (val % 10);
}

// Appends a fixed-width zero-padded integer with 3 or 4 digits using direct ASCII math.
// If val < 1000, prints necessary leading zeroes. Parameter is uint16_t to avoid AVR 16-bit
// int sign conversion when millisec values exceed INT16_MAX.
static inline void appendPadded34(char*& ptr, uint16_t val) {
  if (val >= 1000) {
    *ptr++ = '0' + (val / 1000) % 10;
    *ptr++ = '0' + (val / 100) % 10;
    *ptr++ = '0' + (val / 10) % 10;
    *ptr++ = '0' + (val % 10);
  } else {
    *ptr++ = '0' + (val / 100) % 10;
    *ptr++ = '0' + (val / 10) % 10;
    *ptr++ = '0' + (val % 10);
  }
}

#endif
