// =========================================================================================
// ========================== !!! USER: DO NOT EDIT THIS FILE !!! ==========================
// =========================================================================================

#include "feathergauge_code.h"

// ===========================
// GLOBAL VARIABLE INITIALIZATION
// ===========================
CustomMS5803 pressureSensor;

#if BURST_SAMPLING
  TimeSpan elapsed;
#endif

RTC_DS3231 rtc;
SdFat32 sd;
File32 outputFile;           // Used to open, write to, and close files on the SD card

DateTime timeAtBurstSwitch;  // Time burst switched between sleep and record
DateTime currentDateTime;    // Time of current second
int16_t currentVoltage;      // Voltage of battery, updated every second

// Sampling flag for ISR to main loop communication
volatile bool samplingFlag   = false;
volatile bool resetTimerFlag = false;

// Number of seconds elapsed since the last SD flush (incremented in resetTimer())
uint8_t secondsSinceFlush = 0;

// Number of milliseconds at last 1 Hz interrupt from RTC
unsigned long millisAtInterrupt = 0; 

// # of times the LED should be toggled (on->off = 1 toggle) during the start-up verification phase
uint8_t ledWarmupToggleTarget = 0;

// Current # of times the LED has been toggled
uint8_t ledWarmupToggleCount  = 0;

// True if LED should be toggled only once during start-up
bool ledWarmupManualPulsePending = false;

// ===========================
// SETUP - SENSOR, TIMESTAMP, SD CARD
// ===========================

void setup() {
  power_timer3_disable();
  power_timer4_disable();
  pinMode(LED_PIN, OUTPUT);
  configureLedWarmupIndicator();
  Serial.end();
  // Enabling serial port communication fundamentally breaks RTC timer interrupts (core function)
  // It can be a useful debugging tool, but you should expect the program to behave incorrectly if enabled.
  // Causes the most problems powerDown sleep states, manifests as sudden cutoff in data or incorrect measuring
  // period with millisecond values in the several thousands.
  // Serial.begin(SERIAL_BAUD_RATE);
  // while (!Serial);
  Wire.begin();
  Wire.setClock(TWI_CLOCK_SPEED);

  // DS3231 SQW pin requires an external pull-up resistor. The internal pull-up resistors 
  // included in the 32u4 are too weak for square wave oscillator output but interrupts still work.
  pinMode(RTC_INTERRUPT_PIN, INPUT_PULLUP);
  
  if (!rtc.begin()) {
    if (Serial) Serial.println(F("RTC Failed to initialize"));
    error(2);
    return;
  }
  rtc.disable32K();
  rtc.clearAlarm(1);
  rtc.clearAlarm(2);
  rtc.writeSqwPinMode(DS3231_OFF);

  if (rtc.lostPower()) {
    // This will adjust to the date and time at compilation; recompile everytime MCU is 
    // flashed for accuracy. If the DS3231 has had continous MCU/button battery power since 
    // last program flash, the time will not be changed.

    // **Relying on this to set the correct time is a bad idea**, but it's better than 
    // no date at all
    rtc.adjust(DateTime(F(__DATE__), F(__TIME__)));
    if (Serial) {
      DateTime setTime = rtc.now();
      Serial.print(F("RTC time set to: "));
      Serial.print(setTime.year());
      Serial.print('/');
      Serial.print(setTime.month());
      Serial.print('/');
      Serial.print(setTime.day());
      Serial.print(' ');
      Serial.print(setTime.hour());
      Serial.print(':');
      Serial.print(setTime.minute());
      Serial.print(':');
      Serial.println(setTime.second());
    }
  }
  
  pressureSensor.reset();
  pressureSensor.begin();

  if (Serial) Serial.print(F("Initializing SD card..."));
  
  if (!sd.begin(SD_CARD_SELECT_PIN, SPI_HALF_SPEED)) { 
    if (Serial) Serial.println(F("Card Failed or Not Present"));
    error(ERROR_SD_CARD_FAILED);
    return;
  }

  if (Serial) Serial.println(F("Card Initialized."));
  char fileName[FILENAME_LENGTH];
  // Temporary test mode: append to a known pre-existing file on the SD card.
  char serialNumber[16];
  EEPROM.get(SERIAL_NUMBER_ADDRESS, serialNumber); 
  if (Serial) Serial.println(F("Read EEPROM"));
  makeFileName(fileName, serialNumber);
  
  outputFile.open(fileName, O_WRITE | O_CREAT | O_AT_END); // Opens .csv file

  if (outputFile) {
    setFileTimestampOnce(outputFile); // Set file metadata once; do not register a global callback
    if (Serial) Serial.println(F("File opened"));
    outputFile.print(F("W.G. Num: "));
    outputFile.print(serialNumber);
    outputFile.print(',');
    outputFile.print(F("Timestamp,Pressure [mbar],Temp [deg C],Battery [VDC]"));
    outputFile.println();
    outputFile.sync();
  } else {
    if (Serial) Serial.println(F("error opening datalog-case1"));
    error(ERROR_FILE_OPEN_FAILED);
  }

  currentDateTime = rtc.now();
  currentVoltage = getBatteryVoltage();
  power_adc_disable();

  rtc.disableAlarm(2);
  #if DELAY_START
    delayStartDeepSleepLoop();
    power_adc_enable();
    currentDateTime = rtc.now();
    currentVoltage = getBatteryVoltage();
    power_adc_disable();
  #endif
  // Set alarm to go off 1 second from now, DS3231_A1_PerSecond triggers alarm when seconds match
  rtc.clearAlarm(1);
  rtc.setAlarm1(currentDateTime + TimeSpan(1), DS3231_A1_PerSecond); 
  #if !(BURST_SAMPLING && BURST_SAMPLING_ONE_SAMPLE)
    Timer1.initialize(SAMPLE_TIME);
    Timer1.attachInterrupt(triggerSampling); // Every time Timer1 goes off, calls triggerSampling
    attachInterrupt(digitalPinToInterrupt(RTC_INTERRUPT_PIN), resetTimerInterrupt, FALLING);
  #endif
  #if BURST_SAMPLING
    timeAtBurstSwitch = currentDateTime;
    if (Serial) {
      Serial.print(F("[BURST] Start write window at "));
      Serial.print(timeAtBurstSwitch.hour()); Serial.print(':');
      Serial.print(timeAtBurstSwitch.minute()); Serial.print(':');
      Serial.println(timeAtBurstSwitch.second());
      Serial.print(F("[BURST] WRITE_SECONDS=")); Serial.print(WRITE_SECONDS);
      Serial.print(F(", SLEEP_SECONDS=")); Serial.println(SLEEP_SECONDS);
    }
  #endif
}

// ===========================
// DATA COLLECTION LOOP
// ===========================

void loop() {
    #if BURST_SAMPLING
      // If true, write time ended; flush SD buffer and enter sleep
      if (elapsed.totalseconds() > WRITE_SECONDS || BURST_SAMPLING_ONE_SAMPLE) {
        #if BURST_SAMPLING_ONE_SAMPLE
          performSensorReading();
        #endif
        DateTime endTime = rtc.now(); // endTime taken before flush
        outputFile.flush();
        secondsSinceFlush = 0;
        if (Serial) {
          Serial.print(F("[BURST] End write window at "));
          Serial.print(endTime.hour()); Serial.print(':');
          Serial.print(endTime.minute()); Serial.print(':');
          Serial.println(endTime.second());
          Serial.print("Elapsed time: ");
          Serial.println(elapsed.totalseconds());
        }
        enterBurstDeepSleep(endTime);
      }
    #endif

    if (resetTimerFlag) {
      resetTimer();
      resetTimerFlag = false;
    }

    if (samplingFlag) {
      #if !(BURST_SAMPLING && BURST_SAMPLING_ONE_SAMPLE)
        performSensorReading();
      #endif
      samplingFlag = false;
    }

    if (secondsSinceFlush >= FLUSH_INTERVAL_SECONDS) {
      if (Serial) {
        Serial.print(F("Flushing SD card at time "));
        Serial.println(millis());
      }
      outputFile.flush();
      secondsSinceFlush = 0;
    }
    // Sleep until next sampling time or interrupt from timers/RTC
    // When waking from burst sleep, this idle command means the MCU will sleep until the next ms, 
    // then check the burst flag
    setForeverIdleSleep();
}

// ===========================
// DATA ACQUISITION FUNCTIONS
// ===========================
void performSensorReading() {
  int32_t currentTemperature, currentPressure;
  pressureSensor.getSensorReadings(ADC_4096, ADC_2048, &currentPressure, 
                                &currentTemperature);

  updateLedWarmupIndicator();
  uint16_t millisec = millis() - millisAtInterrupt;

  // This eliminates 99% of cases where the millisecond timer and RTC are exactly in sync, 
  // leading to millisecond overflow, while maintaining an error of +/- 1ms
  // An overflow more than 1000 is untouched so it can be discarded in postprocessing
  millisec = (millisec == 1000) ? 999 : millisec;

  writeToOutputFile(currentDateTime, millisec, currentPressure, currentTemperature, currentVoltage);
}

int16_t getBatteryVoltage() {
  int32_t sensorValue = analogRead(BATTERY_VOLTAGE_PIN);

  // 1. Multiply by scaled constant.
  // 2. Add 32768 (half of 65536) to ensure proper rounding.
  // 3. Bit-shift right by 16 (equivalent to dividing by 65536).
  return (int16_t) (((sensorValue * BATT_FAST_MULT) + 32768) >> 16);
}

// ===========================
// RTC/TIME/SD UTILITIES
// ===========================

void resetTimer() {
  secondsSinceFlush++;
  power_adc_enable();
  // millisAtInterrupt = millis();
  currentDateTime = rtc.now();
  if (Serial) {
    Serial.print(F("Reset timer at: "));
    Serial.print(currentDateTime.year());
    Serial.print('/');
    Serial.print(currentDateTime.month());
    Serial.print('/');
    Serial.print(currentDateTime.day());
    Serial.print(' ');
    Serial.print(currentDateTime.hour());
    Serial.print(':');
    Serial.print(currentDateTime.minute());
    Serial.print(':');
    Serial.println(currentDateTime.second());
  }
  #if BURST_SAMPLING
    elapsed = currentDateTime - timeAtBurstSwitch;
  #endif
  currentVoltage = getBatteryVoltage();
  #if !(BURST_SAMPLING && BURST_SAMPLING_ONE_SAMPLE)
    rtc.clearAlarm(1);
    // rtc.setAlarm1(currentDateTime + TimeSpan(1), DS3231_A1_PerSecond);
  #endif
  power_adc_disable();
}


void makeFileName(char* fileName, char* serialNumber) {
  // Format: WG-00_YYYY-MM-DD_IT-XX.csv (ISO 8601 date) (e.g., WG-08_2026-05-04_IT-00.csv)
  char* curr = fileName;
  DateTime now = rtc.now();
  *curr++ = 'W';
  *curr++ = 'G';
  *curr++ = '-';
  *curr++ = *serialNumber++;
  *curr++ = *serialNumber;
  *curr++ = '_';
  appendInt(curr, (int) now.year());
  *curr++ = '-';
  appendPadded2(curr, (int) now.month());
  *curr++ = '-';
  appendPadded2(curr, (int) now.day());
  *curr++ = '_';
  *curr++ = 'I';
  *curr++ = 'T';
  *curr++ = '-';
  char* startOfIt = curr;
  *curr++ = '0';
  *curr++ = '0';
  *curr++ = '.';
  *curr++ = 'c';
  *curr++ = 's';
  *curr++ = 'v';
  *curr++ = '\0';
  // Find the next available file index for this day
  for (uint8_t fileIndex = 1; fileIndex < 100; fileIndex++) {
    if (!sd.exists(fileName)) {
      break;
    }
    *startOfIt = '0' + (fileIndex / 10);
    *(startOfIt + 1) = '0' + (fileIndex % 10);
  }
  
  if (Serial) {
    Serial.print(F("File name: "));
    Serial.println(fileName);
  }
}

void setFileTimestampOnce(File32& file) {
  DateTime now = rtc.now();
  if (!file.timestamp(T_CREATE | T_WRITE | T_ACCESS, now.year(), now.month(), now.day(),
                      now.hour(), now.minute(), now.second())) {
    if (Serial) Serial.println(F("Failed to set initial file timestamp"));
  }
}

void writeToOutputFile(DateTime now, int millisec, int32_t pressure, 
                       int32_t temperature, int16_t batteryVoltage) {
  char rowBuffer[ROW_BUFFER_SIZE];
  char* ptr = rowBuffer;

  // Date: YYYY/M/D
  appendInt(ptr, (int)now.year());
  *ptr++ = '/';
  appendInt(ptr, (int)now.month());
  *ptr++ = '/';
  appendInt(ptr, (int)now.day());
  *ptr++ = ',';

  // Time: H:MM:SS.mmm
  appendInt(ptr, (int)now.hour());
  *ptr++ = ':';
  appendPadded2(ptr, (int)now.minute());
  *ptr++ = ':';
  appendPadded2(ptr, (int)now.second());
  *ptr++ = '.';
  appendPadded34(ptr, millisec);
  *ptr++ = ',';

  // Pressure: XXXX.X (fixed point, 1 decimal place, units of 0.1 mbar)
  append32Int(ptr, pressure / 10);
  *ptr++ = '.';
  *ptr++ = '0' + (pressure % 10);
  *ptr++ = ',';

  // Temperature: XX.XX (fixed point, 2 decimal places, units of 0.01 C, signed)
  int32_t temp_fixed;
  if (temperature < 0) {
    *ptr++ = '-';
    temp_fixed = -temperature;
  } else {
    temp_fixed = temperature;
  }
  append32Int(ptr, temp_fixed / 100);
  *ptr++ = '.';
  appendPadded2(ptr, (int)(temp_fixed % 100));
  *ptr++ = ',';

  // Voltage: X.XX (fixed point, 2 decimal places, units of 0.01 V)
  appendInt(ptr, (int)(batteryVoltage / 100));
  *ptr++ = '.';
  appendPadded2(ptr, (int)(batteryVoltage % 100));

  *ptr++ = '\r';
  *ptr++ = '\n';

  outputFile.write(reinterpret_cast<const uint8_t*>(rowBuffer), static_cast<size_t>(ptr - rowBuffer));

  const size_t rowLength = static_cast<size_t>(ptr - rowBuffer);
  const uint32_t projectedSize = outputFile.size() + static_cast<uint32_t>(rowLength);

  if (projectedSize > FILE_ROLLOVER_SIZE_BYTES) {
    outputFile.sync();
    outputFile.close();

    char fileName[FILENAME_LENGTH];
    char serialNumber[SERIAL_NUMBER_LENGTH];
    EEPROM.get(SERIAL_NUMBER_ADDRESS, serialNumber);
    makeFileName(fileName, serialNumber);

    if (!outputFile.open(fileName, O_WRITE | O_CREAT | O_AT_END)) {
      if (Serial) Serial.println(F("error opening datalog-case2"));
      error(ERROR_FILE_OPEN_FAILED);
      return;
    }

    setFileTimestampOnce(outputFile);
    outputFile.print(F("W.G. Num: "));
    outputFile.print(serialNumber);
    outputFile.print(',');
    outputFile.print(F("Timestamp,Pressure [mbar],Temp [deg C],Battery [VDC]"));
    outputFile.println();
    outputFile.sync();
  }

  outputFile.write(reinterpret_cast<const uint8_t*>(rowBuffer), rowLength);
}

// ===========================
// SLEEP MANAGEMENT
// ===========================


// When time is set into the future, no sensor readings occur
void delayStartDeepSleepLoop() {
  DateTime startDateTime(START_YEAR, START_MONTH, START_DAY, START_HOUR, START_MINUTE, 0);

  // Configure RTC alarms
  rtc.clearAlarm(1);
  rtc.setAlarm1(startDateTime, DS3231_A1_Hour); // Alarm 1 triggers every day until start time
  attachInterrupt(digitalPinToInterrupt(RTC_INTERRUPT_PIN), deepSleepInterrupt, FALLING);

  // Don't go to sleep if start time has already passed
  DateTime now = rtc.now();

  if (now.unixtime() >= startDateTime.unixtime()) {
    detachInterrupt(digitalPinToInterrupt(RTC_INTERRUPT_PIN));
    rtc.clearAlarm(1);
    return;
  }
  if (Serial) Serial.println(F("Entering delay deep sleep"));

  // Loop until start date is reached
  while (true) {
    // ADC is OFF; ADC_ON setting prevents LowPower from turning it back on after waking up
    LowPower.powerDown(SLEEP_FOREVER, ADC_ON, BOD_OFF);
    delay(50);  // This delay allows MCU components to initialize upon wake-up
    Wire.end(); // The delay, and restarting I2C isn't strictly necessary but qualitatively improves stability
    Wire.begin();
    Wire.setClock(TWI_CLOCK_SPEED);
    // Device has woken up
    now = rtc.now();
    if (now.unixtime() >= startDateTime.unixtime()) {
      detachInterrupt(digitalPinToInterrupt(RTC_INTERRUPT_PIN));
      rtc.clearAlarm(1);
      return; // Exit loop and continue with setup()
    }

    // digitalWrite(LED_PIN, HIGH);
    // delay(ERROR_BLINK_DELAY);
    // digitalWrite(LED_PIN, LOW);
    
    // Not yet at start date, log one sample and go back to sleep
    power_adc_enable();
    int32_t delayPressure, delayTemperature;
    pressureSensor.getSensorReadings(ADC_4096, ADC_2048, &delayPressure, &delayTemperature);
    updateLedWarmupIndicator();
    // Perform voltage reading after sensor reading to give ADC time to settle
    currentVoltage = getBatteryVoltage(); 
    power_adc_disable();
    // Use `now` (current RTC time) and `currentVoltage` directly - currentDateTime and the global
    // voltage are not updated during deep sleep, so they cannot be used here
    writeToOutputFile(now, 0, delayPressure, delayTemperature, currentVoltage);
    outputFile.flush();
    rtc.clearAlarm(1);
  }
}

void enterBurstDeepSleep(DateTime endTime) {
  rtc.clearAlarm(1);
  DateTime now = rtc.now();
  if (now.unixtime() >= endTime.unixtime() + SLEEP_SECONDS - 1) {
    timeAtBurstSwitch = now;
    resetTimer();
    rtc.setAlarm1(currentDateTime + TimeSpan(1), DS3231_A1_PerSecond);
    attachInterrupt(digitalPinToInterrupt(RTC_INTERRUPT_PIN), resetTimerInterrupt, FALLING);
    #if !BURST_SAMPLING_ONE_SAMPLE
      Timer1.restart();
      Timer1.attachInterrupt(triggerSampling);
    #endif
    // Timer1.stop();
    return;
  }
  DateTime nextWake(endTime + TimeSpan(SLEEP_SECONDS));
  if (Serial) {
    Serial.print(F("[BURST] Next wake scheduled at "));
    Serial.print(nextWake.hour()); Serial.print(':');
    Serial.print(nextWake.minute()); Serial.print(':');
    Serial.println(nextWake.second());
  }
  rtc.clearAlarm(1);
  rtc.setAlarm1(nextWake, DS3231_A1_Date);
  attachInterrupt(digitalPinToInterrupt(RTC_INTERRUPT_PIN), burstSleepInterrupt, FALLING);

  // ADC is OFF; ADC_ON setting prevents LowPower from turning it back on after waking up
  LowPower.powerDown(SLEEP_FOREVER, ADC_ON, BOD_OFF);
  millisAtInterrupt = millis();
  delay(50);  // This delay is important to allow MCU components to initialize upon wake-up
  Wire.end();
  Wire.begin();
  Wire.setClock(TWI_CLOCK_SPEED);
  rtc.clearAlarm(1);
  timeAtBurstSwitch = rtc.now();
  resetTimer();
  #if !BURST_SAMPLING_ONE_SAMPLE
    rtc.setAlarm1(currentDateTime + TimeSpan(1), DS3231_A1_PerSecond);
    attachInterrupt(digitalPinToInterrupt(RTC_INTERRUPT_PIN), resetTimerInterrupt, FALLING);
    Timer1.restart();
    Timer1.attachInterrupt(triggerSampling);
  #endif
}

void setForeverIdleSleep() {
  // ADC, timer 3, and timer 4 are set to ON so LowPower library doesn't turn them back on afer 
  // sleep, they are already off
  LowPower.idle(SLEEP_FOREVER, ADC_ON, TIMER4_ON, TIMER3_ON, TIMER1_ON, TIMER0_ON, SPI_OFF, USART1_OFF, 
                TWI_ON, USB_OFF);
}

// ===========================
// ERRORS/TROUBLESHOOTING
// ===========================

void error (uint8_t errno) {
  while (1) {
    uint8_t blinkCount; // Counts error blinks
    for (blinkCount = 0; blinkCount < errno; blinkCount++) {
      digitalWrite(LED_PIN, HIGH);
      delay(ERROR_BLINK_DELAY);
      digitalWrite(LED_PIN, LOW);
      delay(ERROR_BLINK_DELAY);
    }
    for (blinkCount = errno; blinkCount < ERROR_BLINK_CYCLE; blinkCount++) {
      delay(ERROR_PAUSE_DELAY);
    }
  }
}

void configureLedWarmupIndicator() {
  ledWarmupToggleCount = 0;
  ledWarmupToggleTarget = 0;
  ledWarmupManualPulsePending = false;

#if BURST_SAMPLING_ONE_SAMPLE
  ledWarmupManualPulsePending = true;
#else
  uint8_t flashCount = LED_WARMUP_DEFAULT_FLASHES;
  bool useManualPulse = false;
  #if BURST_SAMPLING
    uint32_t availableReadings = WRITE_SECONDS * (uint32_t)SAMPLE_FREQ;
    // Calculate # of flashes that fit within first sampling window
    while (flashCount > 1 && ((uint32_t)flashCount * 2) > availableReadings) {
      flashCount /= 2;
      if (flashCount == 0) {
        flashCount = 1;
        break;
      }
    }
    if (((uint32_t)flashCount * 2) > availableReadings) {
      useManualPulse = true;
    }
  #endif
  if (useManualPulse) {
    ledWarmupManualPulsePending = true;
  } else {
    ledWarmupToggleTarget = flashCount * 2;
  }
#endif

  digitalWrite(LED_PIN, LOW);
}

void updateLedWarmupIndicator() {
  if (ledWarmupManualPulsePending) {
    digitalWrite(LED_PIN, HIGH);
    delay(LED_WARMUP_MANUAL_FLASH_DELAY_MS);
    digitalWrite(LED_PIN, LOW);
    ledWarmupManualPulsePending = false;
    return;
  }

  if (ledWarmupToggleCount >= ledWarmupToggleTarget) {
    return;
  }

  bool ledShouldBeOn = (ledWarmupToggleCount % 2 == 0);
  digitalWrite(LED_PIN, ledShouldBeOn ? HIGH : LOW);
  ledWarmupToggleCount++;

  if (ledWarmupToggleCount >= ledWarmupToggleTarget) {
    digitalWrite(LED_PIN, LOW);
  }
}

// ===========================
// INTERRUPT SERVICE ROUTINES
// ===========================

void triggerSampling() {
    samplingFlag = true;
}

void resetTimerInterrupt() {
  resetTimerFlag = true;
  millisAtInterrupt = millis();
  currentDateTime = currentDateTime + TimeSpan(1);
}

void deepSleepInterrupt() {
  // Do nothing
}

void burstSleepInterrupt() {
  // Do nothing
}
